"""Canonical stock_management contract used by validators and tests."""

OPERATIONAL_TABLES = (
    "pdd_configuration_version",
    "pdd_pdvb_model_version",
    "pdd_distribution_scope_version",
    "pdd_distribution_scope_article",
    "pdd_distribution_scope_pair",
    "pdd_calculation_run",
    "pdd_source_snapshot",
    "pdd_pdvb_publication_batch",
    "pdd_pdvb_publication_stage",
    "pdd_pdvb_estimate",
    "pdd_pdvb_current",
    "pdd_pdvb_quality_issue",
    "pdd_pdvb_backtest_metric",
    "pdd_item_logistics_snapshot",
    "pdd_branch_stock_position",
    "pdd_cd_stock_position",
    "pdd_need_snapshot",
    "pdd_directed_need",
    "pdd_directed_need_line",
    "pdd_directed_need_version",
    "pdd_current_backlog_line",
    "pdd_backlog_source_allocation",
    "pdd_valkimia_import",
    "pdd_valkimia_import_line",
    "pdd_execution_event",
    "pdd_integration_message",
    "pdd_business_event_log",
)
